security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            
            logout:
                path: app_logout

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS}
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/medecin, roles: ROLE_MEDECIN }
        - { path: ^/patient, roles: ROLE_PATIENT }
        - { path: ^/pharmacie, roles: ROLE_PHARMACIE }
        - { path: ^/infermier, roles: ROLE_INFERMIER }