
services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor      # Use Docker volume for vendor
      - node_modules:/var/www/html/node_modules   # Use Docker volume for node_modules
    ports:
      - "9000:9000"
    depends_on:
      - node

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - vendor:/var/www/html/vendor      # Use Docker volume for vendor
      - node_modules:/var/www/html/node_modules   # Use Docker volume for node_modules
    depends_on:
      - php

  node:
    image: node:18
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - node_modules:/var/www/html/node_modules   # Use Docker volume for node_modules
    command: >
      sh -c "npm install && npm run dev"

volumes:
  vendor:
  node_modules:
