services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html:cached
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    ports:
      - "9000:9000"
    depends_on:
      - node

  worker:
    build:
      context: .
    command: php bin/console messenger:consume async --no-interaction
    volumes:
      - .:/var/www/html:cached
      - vendor:/var/www/html/vendor
    depends_on:
      - php

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    depends_on:
      - php

  node:
    image: node:18
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
      - node_modules:/var/www/html/node_modules
    command: [ "sh", "-c", "npm install && npm run watch" ]
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  vendor:
  node_modules: